highlighter: rouge
markdown: kramdown
kramdown:
  auto_ids: true
baseurl: /WWII
permalink: pretty
excerpt_separator: "\n\n"
relative_permalinks: false
exclude: []
script: [
  'js/github.js'
]
name: WWII-player
title: WWII player repository
description: Distribuited World War II a la Wolfenstein on top of Fork-n-Play
